apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog
  name: blog
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: blog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - image: rg.fr-par.scw.cloud/fireto/stigok/blog.stigok.com:latest
        imagePullPolicy: Always
        name: blog
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 250Mi
            cpu: 200m
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blog
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app: blog
  name: blog
spec:
  rules:
    - host: blog.stigok.com
      http:
        paths:
          - backend:
              service:
                name: blog
                port:
                  number: 80
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - blog.stigok.com
      secretName: blog-tls-cert
