name: Continous deployment

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Full revision history
        fetch-depth: 0

    # Because jekyll user (which doesn't exist in this step) needs write
    # access to the build folder in the next step
    - name: Create jekyll build dir
      run: mkdir build && chmod 777 build

    # Build site
    - name: Jekyll builder
      uses: docker://jekyll/builder:3.8
      with:
        args: jekyll build -d build

    # Create new image
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        repository: ${{ github.repository }}
        dockerfile: .deploy/Dockerfile
        path: .
        tags: latest,${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Update Kubernetes deployment
      uses: steebchen/kubectl@v1.0.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      with:
        args: set image deploy/blog blog=${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
