name: Testing the GitHub Pages publication

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    - name: Jekyll builder
      uses: docker://jekyll/builder:3.8
      with:
        entrypoint: /bin/bash
        args: cd $GITHUB_WORKSPACE && jekyll build
