name: Testing the GitHub Pages publication

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    - name: Jekyll builder
      uses: jekyll/builder:3.8
      with:
        args: jekyll build
